version: 2

project_name: fender

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/fender-proxy/fender/cmd.appVersion={{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - format: tar.gz
    name_template: "fender_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: checksums.txt

release:
  github:
    owner: fender-proxy
    name: fender

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
